Fix build failing since https://github.com/TrinityCore/TrinityCore/commit/863ba43c208816a60b7b94d8a3eed9d9c375e840
/TrinityCore/src/server/game/Maps/Map.cpp:2448:22: fatal error: 
      variable 'areaId' is used uninitialized whenever 'if' condition is false
      [-Wsometimes-uninitialized]
        if (GridMap* gmap = const_cast<Map*>(this)->GetGrid(x, y))